services:
  bookmark-service:
    image: bookmark-service:test
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - SERVICE_NAME=bookmark_service
      - REDIS_ADDRESS=redis
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
